services:
  stagingDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  server:
    depends_on:
      stagingDB:
        condition: service_healthy
    environment:
      DB_HOST: prodDB
      CORS_ALLOWED_ORIGINS: https://api.pierre.wns.wilders.dev,https://pierre.wns.wilders.dev
    image: scrip/wns-livecodings-server
    ports:
      - 8081:4000
  client:
    image: scrip/wns-livecodings-client
    ports:
      - 8080:80


