services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  server:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    image: scrip/wns-livecodings-server
    ports:
      - 8080:80
      - 4000:4000
    volumes:
      - ./server/src:/app/src
  client:
    image: scrip/wns-livecodings-client
    ports:
      - 80:80


