FROM keymetrics/pm2:18-alpine as build-stage

RUN apk --no-cache add curl
RUN apk add make g++ python3 git
RUN npm i -g node-pre-gyp

RUN mkdir /app
WORKDIR /app

COPY package.json ./
COPY /pnpm-lock.yaml ./
RUN npm i -g pnpm
RUN pnpm i

COPY tsconfig.json ./
COPY src ./

# tanspile TS into JS for perf
RUN ["npm", "run", "build"]

# the command that starts our app
CMD ["pm2-runtime", "--json", "build/index.js"]