name: Compile and push client and server to staging

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build-and-push-server-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          file: "Dockerfile.production"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wns-livecodings-server:staging
  build-and-push-client-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          file: "Dockerfile.production"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wns-livecodings-client:staging
  notify:
    needs:
      - build-and-push-server-staging
      - build-and-push-client-staging
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.pierre.wns.wilders.dev/hooks/update-staging
